services:
  - type: web
    name: my-static-site
    env: static
    routes:
      - type: rewrite
        source: /*
        destination: /*
    headers:
      - path: /*
        headers:
          - key: X-Robots-Tag
            value: noindex, nofollow
